/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc165InterfacesSupportedSol from "./ERC165InterfacesSupported.sol";
export type { erc165InterfacesSupportedSol };
export type { ERC165MissingData } from "./ERC165MissingData";
