/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AddressToUintMapMock } from "./AddressToUintMapMock";
export type { Bytes32ToBytes32MapMock } from "./Bytes32ToBytes32MapMock";
export type { UintToAddressMapMock } from "./UintToAddressMapMock";
