/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SampleChild } from "./SampleChild";
export type { SampleFather } from "./SampleFather";
export type { SampleGramps } from "./SampleGramps";
export type { SampleHuman } from "./SampleHuman";
export type { SampleMother } from "./SampleMother";
