/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { UUPSUpgradeableMock__factory } from "./UUPSUpgradeableMock__factory";
export { UUPSUpgradeableUnsafeMock__factory } from "./UUPSUpgradeableUnsafeMock__factory";
