/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as myGovernor3Sol from "./MyGovernor3.sol";
export { MyGovernor1__factory } from "./MyGovernor1__factory";
export { MyGovernor2__factory } from "./MyGovernor2__factory";
