/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ContextMock } from "./ContextMock";
export type { ContextMockCaller } from "./ContextMockCaller";
