/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as myGovernor3Sol from "./MyGovernor3.sol";
export type { myGovernor3Sol };
export type { MyGovernor1 } from "./MyGovernor1";
export type { MyGovernor2 } from "./MyGovernor2";
