/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../../../common";

export interface BridgeArbitrumL2MockInterface extends utils.Interface {
  functions: {
    "isTopLevelCall()": FunctionFragment;
    "myCallersAddressWithoutAliasing()": FunctionFragment;
    "relayAs(address,bytes,address)": FunctionFragment;
    "wasMyCallersAddressAliased()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "isTopLevelCall"
      | "myCallersAddressWithoutAliasing"
      | "relayAs"
      | "wasMyCallersAddressAliased"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "isTopLevelCall",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "myCallersAddressWithoutAliasing",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "relayAs",
    values: [string, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "wasMyCallersAddressAliased",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "isTopLevelCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "myCallersAddressWithoutAliasing",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "relayAs", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "wasMyCallersAddressAliased",
    data: BytesLike
  ): Result;

  events: {};
}

export interface BridgeArbitrumL2Mock extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: BridgeArbitrumL2MockInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    isTopLevelCall(overrides?: CallOverrides): Promise<[boolean]>;

    myCallersAddressWithoutAliasing(
      overrides?: CallOverrides
    ): Promise<[string]>;

    relayAs(
      target: string,
      data: BytesLike,
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    wasMyCallersAddressAliased(overrides?: CallOverrides): Promise<[boolean]>;
  };

  isTopLevelCall(overrides?: CallOverrides): Promise<boolean>;

  myCallersAddressWithoutAliasing(overrides?: CallOverrides): Promise<string>;

  relayAs(
    target: string,
    data: BytesLike,
    sender: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  wasMyCallersAddressAliased(overrides?: CallOverrides): Promise<boolean>;

  callStatic: {
    isTopLevelCall(overrides?: CallOverrides): Promise<boolean>;

    myCallersAddressWithoutAliasing(overrides?: CallOverrides): Promise<string>;

    relayAs(
      target: string,
      data: BytesLike,
      sender: string,
      overrides?: CallOverrides
    ): Promise<void>;

    wasMyCallersAddressAliased(overrides?: CallOverrides): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    isTopLevelCall(overrides?: CallOverrides): Promise<BigNumber>;

    myCallersAddressWithoutAliasing(
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    relayAs(
      target: string,
      data: BytesLike,
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    wasMyCallersAddressAliased(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    isTopLevelCall(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    myCallersAddressWithoutAliasing(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    relayAs(
      target: string,
      data: BytesLike,
      sender: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    wasMyCallersAddressAliased(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
