/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as draftErc20PermitSol from "./draft-ERC20Permit.sol";
export * as draftIerc20PermitSol from "./draft-IERC20Permit.sol";
export { ERC20Burnable__factory } from "./ERC20Burnable__factory";
export { ERC20Capped__factory } from "./ERC20Capped__factory";
export { ERC20FlashMint__factory } from "./ERC20FlashMint__factory";
export { ERC20Pausable__factory } from "./ERC20Pausable__factory";
export { ERC20Snapshot__factory } from "./ERC20Snapshot__factory";
export { ERC20Votes__factory } from "./ERC20Votes__factory";
export { ERC20VotesComp__factory } from "./ERC20VotesComp__factory";
export { ERC20Wrapper__factory } from "./ERC20Wrapper__factory";
export { IERC20Metadata__factory } from "./IERC20Metadata__factory";
