/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as uupsLegacySol from "./UUPSLegacy.sol";
export type { uupsLegacySol };
import type * as uupsUpgradeableMockSol from "./UUPSUpgradeableMock.sol";
export type { uupsUpgradeableMockSol };
