/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as uupsLegacySol from "./UUPSLegacy.sol";
export * as uupsUpgradeableMockSol from "./UUPSUpgradeableMock.sol";
